# Generated by Django 3.0.8 on 2020-07-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='pub_date',
        ),
    ]
